### ISSUE TITLE
Feature request: Day 2: Change the number of VMs created by the vRA blueprint

### ISSUE THREAD

**Issue by spbarbieri** [vmware-archive/terraform-provider-vra7#47]
I have a vRA blueprint that contains a cluster of 1 to 5 EC2 Servers:

![image](https://user-images.githubusercontent.com/25961207/74564397-02651600-4f3d-11ea-846a-a19b10fe8d14.png)

I have a terraform configuration that deploys this blueprint
```
resource "vra7_deployment" "min_max" {
  wait_timeout = "20"
  catalog_item_name = "min-max"

  resource_configuration = {
    EC2_Cluster._cluster = "3"
    EC2_Cluster.ip_address = ""
  }
}
```

This successfully deploys my blueprint and creates 3 VMs. 

If I change **EC2_Cluster._cluster = "3"** to **EC2_Cluster._cluster = "5"** and run Terraform apply the apply completes successfully but does nothing. I don't get 2 new VMs.

Is this expected? Am I doing something incorrectly?

**Comment by MaciejKaras** [comment]
We've also stumbled with the same problem. It does not scale down nor scale down.

**Comment by t-settle** [comment]
I too am having the issue of VRA not modifying the # of instances in my deployment if I change the value and apply.

I am doing:
  deployment_configuration = {
    "_number_of_instances" = "2"
  } 

How were you able to get EC2_Cluster._cluster = "3" to work? Every time I use _cluster I get an error like this:

resource_configuration = {
"vm._cluster" = "2"
}

Error: Resource Machine Request Failed: vRealize API: [{Code:20117 Message:The data specified within the request is invalid. SystemMessage:The data specified within the request is invalid.} {Code:11003 Message:The value of the '_cluster' field cannot be more than 1. SystemMessage:The value of the field with id _cluster cannot be more than 1.} {Code:400 Message: SystemMessage:}]

@Prativa20 - you seem to know most about this from the other issues I've looked at. Any thoughts?

**Comment by Prativa20** [comment]
The scale in/out is a day 2 action and this feature is not implemented yet. Thanks for opening this feature request. I will update soon about the timeline.

**Comment by feewald** [comment]
@Prativa20 any update on this? any Estimated date of when will it be implemented?
Thanks

**Comment by Prativa20** [comment]
This issue is fixed in latest version, v1.0.0. Added a 'cluster' property in the schema under resource_configuration to support scaling. Refer to documentation and README for details

**Comment by spbarbieri** [comment]
@Prativa20 Thank you for the update. I still can't get this to work.

I have a vRA blueprint that contains a cluster of 1 to 5 EC2 Servers:

![image](https://user-images.githubusercontent.com/25961207/81231586-6558cd00-8fc1-11ea-9e7d-cb6111d03593.png)

Here is my Terraform template:

```
variable "num_vms" {}

resource "vra7_deployment" "min_max-2" {
  count = "1"
  wait_timeout = "30"
  catalog_item_name = "spb-min-max-2"
  resource_configuration = {
     component_name = "EC2_Cluster"
     cluster = "${var.num_vms}"
  }
}
```

* I run terraform init which brings down terraform-provider-vra7_v1.0.1_x4
* I run terraform apply and set num_vms = 2.  This successfully deploys my blueprint and creates 2 VMs.
* I run terraform apply and set num_vms = 3. This successfully completes and says "Apply complete! Resources: 0 added, 1 changed, 0 destroyed."

When I check vRA, there aren't any new items. When I check AWS, there aren't any new VMs. Have I set up my Terraform template correctly?

**Comment by Prativa20** [comment]
@spbarbieri Can you please share the vra-terraform.log? Also, can you try Scale In, making the cluster as 1?

**Comment by spbarbieri** [comment]
@Prativa20 How do I produce the vra-terraform.log? Also, terraform apply with num_vms = 1 did not remove any VMs.

**Comment by feewald** [comment]
@Prativa20 could you please provide an update for @spbarbieri comment?
Thanks.

**Comment by feewald** [comment]
Hi @Prativa20 Could you please help us?
It is blocking one of our users.
Thanks.

**Comment by Prativa20** [comment]
@spbarbieri You will find the vra-terraform.log file in the same directory where you have your main.tf

**Comment by spbarbieri** [comment]
@Prativa20 I retried the scenario using a blueprint that creates VMs in VMware. It works most of the time. I had a few issues while testing, but all in all, it works well. I am unable to try this with a blueprint that creates VMs in AWS. We have a problem with our vRA system with connections to AWS.
